Readme updated - Added Floating IP
koalalorenzo/python-digitalocean pull request #361
Opened 2023-01-27 17:35 UTC by SanjaySRocks

Added example of creating floating and deleting it in readme

2023-02-13 13:07 UTC, koalalorenzo requested changes

2023-02-13 13:07 UTC, koalalorenzo commented on README.md
> +        print(release_static_ip) # returns True on success
Any reason for extra indentation here?

```suggestion
# To Create IP
static_ip = floating_ip.reserve()
print(static_ip)

# To Delete IP
release_static_ip = floating_ip.destroy()
print(release_static_ip) # returns True on success
```

2023-02-13 13:46 UTC, SanjaySRocks commented on README.md
> +        print(release_static_ip) # returns True on success
No, thanks for update.

2023-03-25 20:59 UTC, koalalorenzo approved these changes

2023-03-25 20:59 UTC, merged